site_name: WICWIU
site_author: HGU DL Lab
repo_name: WICWIU
repo_url: https://github.com/WICWIU/WICWIU
copyright: Copyright &copy; 2018-2020 HGU DL Lab

##################################################
########## Documentation Structure ###############
nav:
  - Home: index.md
  - About: about.md
  - API: api.md
  - 논문 정리: 
    - ResNet: paper/resnet.md
  # - WICWIU 딥러닝 가이드: usage/usage.md
  - WICWIU 개발 가이드: 
    - WICWIU: 
      - 1. About WICWIU: dev/wicwiu/about.md
      - 2. WICWIU 신경망 구성: dev/wicwiu/nn.md
      - 3. WICWIU 로 학습하기: dev/wicwiu/learn.md
      - 4. WICWIU 코드 같이보기: dev/wicwiu/code.md
    - Git:
      - Collaborate with Git: dev/Git/git.md
      - Commit/PR protocol: dev/Git/message.md
      - Update forked repo: dev/Git/update.md
    - GPU Acceleration:
      - cuda: dev/GPU/cuda.md
    - Makefile: 
      - Makefile 기본: dev/makefile/makefile.md
      - Makefile 고급: dev/makefile/makefile2.md
    - CLI: 
      - CLI: dev/cli/cli.md
      - zsh: dev/cli/zsh.md
      - tmux: dev/cli/tmux.md
  - WICWIU 지식동기화: 
    - fewshot diary: 
      # - Step 0. 방법론: sync/fewshot/step0.md
      - Step 1. Data &rarr; Tensor:
        - Analysis&#58; LFW 1: sync/fewshot/step1-1.md
        - Analysis&#58; LFW 2: sync/fewshot/step1-2.md
        - Coding&#58; PNG, CImg: sync/fewshot/step1-3.md
      - Step 2. 순전파: sync/fewshot/step2.md
      - Step 3. 역전파: sync/fewshot/step3.md
      - Step 4. 최적화: sync/fewshot/step4.md
  - 이곳에 문서 작성하기:
    - Step 1. Markdown 파일: write/markdown.md
    - Step 2. 소스코드 설명하기: write/code.md
    - Step 3. 고오급 포매팅: write/format.md
    - Step 4. Admonitions: write/admonitions.md
    - Step 5. 컨텐츠 탭: write/tab.md
    - Step 6. 버튼 넣기: write/button.md
    - Step 7. 수식 보여주기: write/math.md
    - Step 8. API 작성: write/api.md
  # - test: test.md
####### END of Documentation Structure ###########
##################################################

theme: 
  name: material
  palette:
    scheme: slate
    primary: indigo
    # scheme: default
    # primary: deep purple
  language: kr
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.ico

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.js
  - javascripts/config.js
  - javascripts/all.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.css
  - stylesheets/gradient-dark.css
  - stylesheets/config.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WICWIU

markdown_extensions:
  - toc:
      permalink: "&para;"
      baselevel: 2
      toc_depth: 2-3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true